# Generated by Django 5.2.3 on 2025-07-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Series'},
        ),
    ]
