# Generated by Django 5.2.3 on 2025-07-09 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articleseries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='no content yet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified'),
        ),
    ]
